# Set the base image to use to Ubuntu
FROM osixia/openldap:1.2.3

# Set the file maintainer
MAINTAINER Ozgur Eroglu

ADD bootstrap /container/service/slapd/assets/config/bootstrap
#ADD ./base.ldif /etc/ldap/base.ldif
#ADD ./ahenkler.ldif /etc/ldap/ahenkler.ldif
#ADD ./lider_console_user.ldif /etc/ldap/lider_console_user.ldif
#ADD ./liderahenk.ldif /tmp/liderahenk.ldif


# Port to expose
#EXPOSE 3306
