# Set the base image to use to Ubuntu
FROM osixia/openldap:1.2.3

# Set the file maintainer
MAINTAINER Ozgur Eroglu


#ADD ./mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf

# Port to expose
#EXPOSE 3306
